[package]
name = "mathlikeanim-rs"
version = "0.5.5"
edition = "2021"
readme = "README.md"
description = "A Rust library for creating mathematical animations"
license = "MIT"
repository = "https://github.com/MathItYT/mathlikeanim-rs"
exclude = [
    "/target",
    "*.svg",
    "*.mp4",
    "*.tex",
    "*.log",
    "*.aux",
    "*.dvi",
    "node_modules",
    "pkg",
    "package-lock.json",
    "package.json",
    "webpack.config.js",
    "app.yaml",
    ".gcloudignore",
]
keywords = ["animation", "graphics", "easing", "transitions", "WebAssembly"]
categories = ["mathematics", "graphics", "wasm"]

[dependencies]
js-sys = "0.3.67"
lightningcss = "1.0.0-alpha.52"
svg = "0.15.0"
wasm-bindgen = "0.2.90"
web-sys = { version="0.3.67", features=[
    'CanvasRenderingContext2d',
    'Document',
    'Element',
    'HtmlCanvasElement',
    'Window',
    'ImageData',
    'HtmlImageElement',
    'CanvasPattern',
    'CanvasGradient',
    'HtmlDivElement',
] }
wasm-bindgen-futures = "0.4.40"
uuid = { version="0.8.2", features=["wasm-bindgen", "v4"] }

[lib]
crate-type = ["cdylib", "rlib"]
