[package]
name = "mathlikeanim-rs"
version = "0.3.0"
edition = "2021"
readme = "README.md"
description = "A Rust library for creating mathematical animations"
license = "MIT"
repository = "https://github.com/MathItYT/mathlikeanim-rs"
exclude = [
    "/target",
    "*.svg",
    "*.mp4",
    "*.tex",
    "*.log",
    "*.aux",
    "*.dvi",
    "node_modules",
    "pkg",
    "package-lock.json",
    "package.json",
    "webpack.config.js",
]
keywords = ["animation", "graphics", "easing", "transitions", "WebAssembly"]
categories = ["mathematics", "graphics", "wasm"]

[dependencies]
js-sys = "0.3.67"
lightningcss = "1.0.0-alpha.52"
svg = "0.15.0"
wasm-bindgen = "0.2.90"
web-sys = { version="0.3.67", features=[
    'CanvasRenderingContext2d',
    'Document',
    'Element',
    'HtmlCanvasElement',
    'Window',
    'ImageData'
] }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
async-std = {version="1.12.0", features=["attributes"]}
wasm-bindgen-futures = "0.4.40"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cairo-rs = "0.18.5"
indicatif = "0.17.7"

[workspace]
members = [
    "examples/wasm_example"
]
