[package]
name = "mathlikeanim-rs"
version = "0.5.7"
edition = "2021"
readme = "README.md"
description = "A Rust library for creating mathematical animations"
license = "MIT"
repository = "https://github.com/MathItYT/mathlikeanim-rs"
exclude = [
    "/target",
    "*.svg",
    "*.mp4",
    "*.tex",
    "*.log",
    "*.aux",
    "*.dvi",
    "node_modules",
    "pkg",
    "package-lock.json",
    "package.json",
    "webpack.config.js",
    "app.yaml",
    ".gcloudignore",
]
keywords = ["animation", "graphics", "easing", "transitions", "WebAssembly"]
categories = ["mathematics", "graphics", "wasm"]

[dependencies]
js-sys = "0.3.69"
lightningcss = "1.0.0-alpha.57"
svg = "0.17.0"
wasm-bindgen = "0.2.92"
web-sys = { version="0.3.69", features=[
    'CanvasRenderingContext2d',
    'Document',
    'Element',
    'HtmlCanvasElement',
    'Window',
    'ImageData',
    'HtmlImageElement',
    'CanvasPattern',
    'CanvasGradient',
    'HtmlDivElement',
    'Url',
    'MediaRecorder',
    'MediaStream',
    'Blob',
    'BlobPropertyBag'
] }
wasm-bindgen-futures = "0.4.42"
uuid = { version="1.8.0", features=["v4", "js"] }

[lib]
name = "mathlikeanim_rs"
crate-type = ["cdylib", "rlib"]
