[package]
name = "mathlikeanim-rs"
version = "0.1.0"
edition = "2021"
readme = "README.md"
exclude = [
    "/target",
    "temp*.svg",
    "temp.typ",
    "*.mp4",
    "*.tex",
    "*.log",
    "*.aux",
    "*.dvi"
]

[dependencies]
cairo-rs = "0.18.5"
indicatif = "0.17.7"
js-sys = "0.3.67"
lightningcss = "1.0.0-alpha.52"
svg = "0.15.0"
wasm-bindgen = "0.2.90"
web-sys = { version="0.3.67", features=[
    'CanvasRenderingContext2d',
    'Document',
    'Element',
    'HtmlCanvasElement',
    'Window',
    'ImageData'
] }

