pub mod draw_stroke_then_fill;
pub mod scale_in_place;
pub mod fade;
pub mod animation_group;
pub mod morph_shape;
pub mod grow_arrow;
pub mod create;
pub mod grow_from_center;
pub mod shift_animation;
#[cfg(feature = "browser")]
pub mod move_camera;
pub mod spinning_grow;
pub mod rotate_animation;
pub mod show_temporarily;
pub mod set_fill_animation;
pub mod set_stroke_animation;
#[cfg(feature = "browser")]
pub mod move_camera_svg;
#[cfg(feature = "node")]
pub mod move_camera_node;
pub mod wasm_interface;
